encryption:
  - hash: sha512
    cipher: aes-xts-plain64
    key_size: 256
    mapping:
      crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116: /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836116
      crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122: /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836122


lvm:
  pvs:
    - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116
    - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122
    - /dev/nvme0n1p3
  vgs:
    ubuntu-vg:
      pvs:
        untagged:
          - /dev/nvme0n1p3
      lvs:
        ubuntu-lv:
          size: rest
          layout: linear
    vg_tmp:
      pvs:
        untagged:
          - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116
          - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122
      lvs:
        lv_tmp:
          size: rest
          layout: linear

zfs:
  - pool: workspace
    vdevs:
      - type: raidz2
        devices:
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKA2AEE
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAEELE
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAG5UE
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGX7E
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGZME
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKANGLE
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAR28E
          - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKASAJE
    datasets:
      - name: workspace
        mountpoint: /mnt/workspace
        compression: lz4
        encryption: aes-256-gcm
        atime: off
        ashift: 12 # physical sector size of hard disks is 4094 (smartctl -i)

filesystems:
  - device: /dev/disk/by-id/dm-uuid-LVM-1lww283aM1j6J7zJP4ch7I5v0lz2JPwBSLbvoO4SAjoCJcv5M2rr7TYIx8uo3YNa
    type: ext4
    mount: /
    options: defaults
    pass: 1
  - device: /dev/disk/by-uuid/01fc0927-c5a9-435a-80e6-230139e4f1d2
    type: ext4
    mount: /boot
    options: defaults
    pass: 1
  - device: /dev/disk/by-uuid/74E8-F2B2
    type: vfat
    mount: /boot/efi
    options: defaults
    pass: 1
  - device: /dev/vg_tmp/lv_tmp
    type: ext4
    mount: /mnt/tmp
    options: noauto,relatime
    pass: 2

permissions:
  /mnt/workspace:
    user: jkoester
    group: koesterlab
    setgid: true
    read: group
    write: group
  /mnt/tmp:
    user: jkoester
    group: koesterlab
    read: group
    write: group
    setgid: true
