partitions:
  - type: primary
    start: 1
    end: -1
    devices:
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKA2AEE
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAEELE
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAG5UE
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGX7E
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGZME
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKANGLE
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAR28E
      - /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKASAJE
      - /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836116
      - /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836122


encryption:
  - hash: sha512
    cipher: aes-xts-plain64
    key_size: 256
    mapping:
      crypt_hdd_WDC_WUH722020BL_STKE2AEE: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKA2AEE
      crypt_hdd_WDC_WUH722020BL_STKEEELE: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAEELE
      crypt_hdd_WDC_WUH722020BL_STKEG5UE: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAG5UE
      crypt_hdd_WDC_WUH722020BL_STKEGX7E: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGX7E
      crypt_hdd_WDC_WUH722020BL_STKEGZME: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAGZME
      crypt_hdd_WDC_WUH722020BL_STKENGLE: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKANGLE
      crypt_hdd_WDC_WUH722020BL_STKER28E: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKAR28E
      crypt_hdd_WDC_WUH722020BL_STKESAJE: /dev/disk/by-id/scsi-SATA_WDC_WUH722020BL_STKASAJE
      crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116: /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836116
      crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122: /dev/disk/by-id/scsi-SNVMe_SAMSUNG_MZQL27T6_S6CKNA0Y836122


lvm:
  pvs:
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKA2AEE
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAEELE
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAG5UE
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAGX7E
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAGZME
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKANGLE
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAR28E
    - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKASAJE
    - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116
    - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122
  vgs:
    vg_tmp:
      pvs:
        - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836116
        - /dev/mapper/crypt_ssd_SAMSUNG_MZQL27T6_S6CKNA0Y836122
      lvs:
        lv_tmp:
          size: rest
          layout: linear
    vg_workspace:
      pvs:
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKA2AEE
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAEELE
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAG5UE
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAGX7E
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAGZME
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKANGLE
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKAR28E
        - /dev/mapper/crypt_hdd_WDC_WUH722020BL_STKASAJE
      lvs:
        lv_workspace:
          size: rest
          layout: raid5

filesystems:
  - device: /dev/disk/by-id/dm-uuid-LVM-1lww283aM1j6J7zJP4ch7I5v0lz2JPwBSLbvoO4SAjoCJcv5M2rr7TYIx8uo3YNa
    type: ext4
    mount: /
    options: defaults
    pass: 1
  - device: /dev/disk/by-uuid/01fc0927-c5a9-435a-80e6-230139e4f1d2
    type: ext4
    mount: /boot
    options: defaults
    pass: 1
  - device: /dev/disk/by-uuid/74E8-F2B2
    type: vfat
    mount: /boot/efi
    options: defaults
    pass: 1
  - device: /dev/vg_tmp/lv_tmp
    type: ext4
    mount: /mnt/tmp
    options: noauto
    pass: 2
  - device: /dev/vg_workspace/lv_workspace
    type: ext4
    mount: /mnt/workspace
    options: noauto
    pass: 2

permissions:
  /mnt/workspace:
    user: jkoester
    group: koesterlab
    setgid: true
    read: group
    write: group
  /mnt/tmp:
    user: root
    group: root
    read: others
    write: others
